#!/usr/bin/env python3

import sys
import time

import config
import proc
import sway
import util

from util import verbose

def sway_loop(callback):
  s = sway.Sway()
  s.subscribe("window")
  while True:
    e = s.read_event(sway.EVENT_WINDOW)
    if e["change"] == "focus":
      c = e["container"]
      callback(c["app_id"], c["pid"])

def main():
  now = time.time()
  for fn in config.INTERESTING.values():
    for fn2 in fn(now):
      fn2(False)

  last = None
  def callback(name, pid):
    nonlocal last
    if pid is None:
      exe = None
    else:
      exe = proc.lookup_exe(pid)

    verbose("focus switch to", (name, pid, exe))
    now = time.time()

    l, last = last, None
    if l:
      for fn in l(now):
        fn(False)

    if exe is None:
      return

    l = config.INTERESTING.get(exe)
    if l is None:
      return

    verbose("switched to", exe)
    for fn in l(now):
      fn(True)
    last = l

  try:
    sway_loop(callback)
  except KeyboardInterrupt:
    pass
  finally:
    now = time.time()
    for fn in config.INTERESTING.values():
      for fn2 in fn(now):
        fn2(True)

if __name__ == "__main__":
  args = sys.argv[1:]
  if "-v" in args or "--verbose" in args:
    util.VERBOSE = True

  main()
