#!/usr/bin/env python3

import sys

import config
import proc
import sway
import util

from util import verbose

def sway_loop(callback):
  s = sway.Sway()
  s.subscribe("window")
  while True:
    e = s.read_event(sway.EVENT_WINDOW)
    if e["change"] == "focus":
      c = e["container"]
      callback(c["app_id"], c["pid"])

def main():
  for fn in config.INTERESTING.values():
    for fn2 in fn():
      fn2(False)

  last = None
  def callback(name, pid):
    nonlocal last
    if pid is None:
      exe = None
    else:
      exe = proc.lookup_exe(pid)

    verbose("focus switch to", (name, pid, exe))

    l, last = last, None
    if l:
      for fn in l():
        fn(False)

    if exe is None:
      return

    l = config.INTERESTING.get(exe)
    if l is None:
      return

    verbose("switched to", exe)
    for fn in l():
      fn(True)
    last = l

  sway_loop(callback)

if __name__ == "__main__":
  args = sys.argv[1:]
  if "-v" in args or "--verbose" in args:
    util.VERBOSE = True

  main()
