#!/usr/bin/env python3

import x
import nicer
import proc
import config
import os
import sys

VERBOSE = False

def verbose(*args):
  if VERBOSE:
    print(*args, file=sys.stderr)

def set_priority(pid, priority):
  nicer.setpriority(os.PRIO_PROCESS, pid, priority)

def main():
  for fn in config.INTERESTING.values():
    for pid, _, inactive_priority in fn():
      set_priority(pid, inactive_priority)

  last = None
  def callback(name, pid):
    nonlocal last
    if pid is None:
      exe = None
    else:
      exe = proc.lookup_exe(pid)

    l, last = last, None
    if l:
      for pid, _, inactive_priority in l():
        set_priority(pid, inactive_priority)

    if exe is None:
      return

    l = config.INTERESTING.get(exe)
    if l is None:
      return

    verbose("switched to", exe)
    for pid, active_priority, _ in l():
      set_priority(pid, active_priority)
    last = l

  x.run(callback)

if __name__ == "__main__":
  args = sys.argv[1:]
  if "-v" in args or "--verbose" in args:
    VERBOSE = True

  main()
